# Generated by Django 2.2.12 on 2020-11-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darah', '0002_pasien_ttl'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasien',
            name='golongan_darah',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
