# Generated by Django 2.2.12 on 2020-11-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darah', '0003_pasien_golongan_darah'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasien',
            name='no_pasien',
        ),
        migrations.AlterField(
            model_name='pasien',
            name='alamat_pasien',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
